const test=require('node:test');const assert=require('node:assert/strict');const E=require('../assets/js/autonomy-engine');const data=require('../_data/autonomy_lab.json');
test('placement, upgrade and recycling enforce energy, occupancy and terminal boundaries',()=>{const s=E.start(data.levels[0]);assert.ok(E.place(s,'lotus',0,0));assert.equal(s.energy,180);assert.equal(E.place(s,'vine',0,0),false);assert.equal(E.place(s,'lotus',3,0),false);assert.equal(E.place(s,'lotus',0,5),false);assert.equal(E.place(s,'__proto__',0,1),false);assert.ok(E.upgrade(s,0,0));assert.equal(E.upgrade(s,0,0),false);assert.ok(E.reclaim(s,0,0));assert.equal(s.energy,187);s.phase='won';assert.equal(E.place(s,'sprout',0,0),false);});
test('each authored level admits a finite winning defence with real energy costs',()=>{for(const l of data.levels){const s=E.start(l);for(let r=0;r<3;r++)E.place(s,'lotus',r,0);E.place(s,'sprout',1,1);let n=0;while(!['won','lost'].includes(s.phase)&&n++<2500){if(s.phase==='build')assert.ok(E.launch(l,s));for(let r=0;r<3;r++){if(!s.plants.some(p=>p.row===r&&p.col===2))E.place(s,'lotus',r,2);if(!s.plants.some(p=>p.row===r&&p.col===4))E.place(s,'vine',r,4);}if(!s.plants.some(p=>p.kind==='nexus'))E.place(s,'nexus',1,3);for(const p of s.plants)if(p.kind==='lotus')E.upgrade(s,p.row,p.col);E.step(l,s);assert.ok(s.energy>=0&&s.energy<=400);assert.ok(s.enemies.every(e=>Number.isFinite(e.x)&&e.hp>0));}assert.equal(s.phase,'won',l.id);assert.equal(s.wave,l.waves.length);assert.ok(E.score(s)>0);assert.ok(s.responses>0);}});
test('unprotected lanes lose; intermissions and finished rounds never advance by themselves',()=>{const l=data.levels[0],s=E.start(l);E.step(l,s);assert.equal(s.tick,0);E.launch(l,s);let n=0;while(s.phase==='wave'&&n++<500)E.step(l,s);assert.equal(s.phase,'lost');assert.equal(s.life,0);const tick=s.tick;E.step(l,s);assert.equal(s.tick,tick);assert.equal(E.launch(l,s),false);});
test('local feedback conserves idle charge, regrows barriers and repairs nearby damage',()=>{const l=data.levels[0],s=E.start(l);E.place(s,'lotus',0,0);E.place(s,'vine',1,2);E.place(s,'nexus',1,1);E.launch(l,s);s.queue=[{at:200,row:2,kind:'stone'}];const vine=s.plants.find(p=>p.kind==='vine');vine.hp=70;for(let i=0;i<10;i++)E.step(l,s);assert.equal(s.plants[0].charge>2,true);assert.equal(s.shots.length,0);assert.ok(vine.hp>70);assert.ok(s.responses>0);});
test('Nexus slowdown responds to a nearby crowd, not an empty field',()=>{const l=data.levels[0],s=E.start(l);E.place(s,'nexus',1,1);E.launch(l,s);s.queue=[{at:200,row:2,kind:'stone'}];E.step(l,s);assert.equal(s.responses,0);s.enemies=[0,1].map((r,i)=>({id:20+i,kind:'stone',row:r,x:3,hp:105,maxHp:105,slow:0}));E.step(l,s);assert.ok(s.enemies.every(e=>e.slow>0));assert.ok(s.events.some(e=>e.kind==='slow'));});
test('local records reject corrupt state and unknown levels without affecting other lab keys',()=>{assert.deepEqual(E.restore('{bad',data.levels),E.restore(null,data.levels));const r=E.restore({version:1,level:'__proto__',best:{'autonomy-1':3,'autonomy-2':99,unknown:2}},data.levels);assert.deepEqual(r.best,{'autonomy-1':3});assert.equal(r.level,data.levels[0].id);});

test('quick setup charges real costs and never overwrites an existing or active defence',()=>{
  const s=E.start(data.levels[0]);assert.equal(E.arrange(s),true);assert.equal(s.energy,20);assert.equal(s.plants.length,4);assert.deepEqual(s.plants.filter(p=>p.kind==='lotus').map(p=>p.row),[0,1,2]);const before=JSON.stringify(s);assert.equal(E.arrange(s),false);assert.equal(JSON.stringify(s),before);
  const low=E.start(data.levels[0]);low.energy=219;assert.equal(E.arrange(low),false);assert.equal(low.plants.length,0);assert.equal(low.energy,219);
  const active=E.start(data.levels[0]);E.launch(data.levels[0],active);assert.equal(E.arrange(active),false);assert.equal(active.plants.length,0);
});
