const test=require('node:test'),assert=require('node:assert/strict'),E=require('../assets/js/network-engine'),data=require('../_data/network_lab.json');
const count=s=>s.delivered+s.stations.reduce((n,a)=>n+a.queue.length,0)+s.trains.reduce((n,t)=>n+t.cargo.length,0);
test('route editing validates endpoints, allows true shared-station transfers and preserves passengers',()=>{
 const s=E.start(data,data.levels[0]);assert.ok(E.connect(s,0,'A','D'));assert.ok(E.connect(s,0,'D','F'));assert.ok(E.connect(s,1,'B','D'));assert.ok(E.connect(s,1,'D','E'));assert.deepEqual(E.path(s,'A','square'),{next:'D',line:0});assert.equal(E.connect(s,0,'D','C'),false);assert.equal(E.setRoute(s,0,['A','A']),false);assert.equal(E.setRoute(s,3,['A','B']),false);assert.equal(E.tap(s,0,'__proto__'),false);assert.equal(E.sample(s),false);
 E.launch(s);for(let i=0;i<80;i++)E.step(s,data.levels[0]);assert.equal(count(s),s.spawned);assert.ok(E.setRoute(s,0,['A','B','C']));assert.equal(count(s),s.spawned);assert.ok(s.trains.every(t=>t.cargo.length<=E.capacity));
});
test('line crossings without a shared stop never create a transfer',()=>{const s=E.start(data,data.levels[0]);E.setRoute(s,0,['A','F']);E.setRoute(s,1,['B','E']);assert.equal(E.path(s,'A','square'),null);E.setRoute(s,0,['A','D','F']);E.setRoute(s,1,['B','D','E']);assert.ok(E.path(s,'A','square'));});
test('a hub outage disconnects upstream demand; a bypass changes the outcome with the same stations',()=>{
 const l=data.levels[0],s=E.start(data,l);E.sample(s);E.launch(s);s.stations[0].queue.push({id:999,target:'square',created:0});s.spawned++;assert.ok(E.path(s,'A','square'));assert.ok(E.fault(s,'D',12));assert.equal(E.path(s,'A','square'),null);assert.ok(E.impact(s).includes('A'));E.setRoute(s,2,['A','B','C']);assert.ok(E.path(s,'A','square'));assert.equal(E.impact(s).includes('A'),false);assert.ok(E.repair(s));assert.equal(s.repairs,0);assert.equal(E.repair(s),false);
});
test('all authored challenges can be won with bounded real-capacity trains and no invented riders',()=>{
 for(const l of data.levels){const s=E.start(data,l);E.sample(s);E.addTrain(s,0);E.launch(s);let steps=0;while(s.phase==='play'&&steps++<1000){if(s.fault&&s.repairs)E.repair(s);if(E.active(s,'E')&&!s.routes[1].includes('E'))E.setRoute(s,1,['B','D','E']);if(E.active(s,'F')&&!s.routes[0].includes('F'))E.setRoute(s,0,['A','D','F']);E.step(s,l);assert.equal(count(s),s.spawned);assert.ok(s.trains.every(t=>t.cargo.length<=4));assert.ok(s.stations.every(n=>Number.isFinite(n.heat)));}assert.equal(s.phase,'won',l.id+': '+s.delivered);assert.ok(E.score(s,l)>0);assert.ok(steps<1000);}
});
test('bad service can fail and terminal states do not advance; setup never auto-runs',()=>{
 const l=data.levels[0],s=E.start(data,l);assert.equal(E.step(s,l),false);assert.equal(E.launch(s),false);E.connect(s,0,'A','B');E.launch(s);let i=0;while(s.phase==='play'&&i++<1000)E.step(s,l);assert.equal(s.phase,'lost');assert.ok(s.reason);const before=JSON.stringify(s);assert.equal(E.step(s,l),false);assert.equal(E.connect(s,1,'C','E'),false);assert.equal(JSON.stringify(s),before);
});
test('load, spare trains, faults and save data have finite boundaries',()=>{const l=data.levels[0],s=E.start(data,l);assert.equal(E.addTrain(s,0),false);E.sample(s);assert.ok(E.addTrain(s,0));assert.equal(E.addTrain(s,1),false);E.launch(s);assert.equal(E.step(s,l,Infinity),false);assert.equal(E.step(s,l,5),false);assert.equal(E.fault(s,'__proto__'),false);assert.ok(E.fault(s));assert.equal(E.fault(s),false);for(let i=0;i<61;i++)E.step(s,l);assert.equal(s.fault,null);assert.equal(E.fault(s),false);assert.deepEqual(E.restore('{bad',data.levels),E.restore(null,data.levels));assert.deepEqual(E.restore({version:1,level:'__proto__',best:{'network-1':{stars:9,delivered:99}}},data.levels),E.restore(null,data.levels));});

test('the external city controls growth and river crossings; hidden stops cannot be connected early',()=>{const l=data.levels[2],s=E.start(data,l);assert.equal(E.active(s,'E'),false);assert.equal(E.setRoute(s,0,['A','E']),false);E.sample(s);E.launch(s);while(s.time<20)E.step(s,l);assert(E.active(s,'E'));assert.equal(E.active(s,'F'),false);while(s.time<38)E.step(s,l);assert(E.active(s,'F'));assert(E.setRoute(s,0,['A','D','F']));assert(E.setRoute(s,1,['B','D','E']));assert.equal(E.crossings(s),2);assert.equal(E.setRoute(s,2,['C','F']),false);assert(E.setRoute(s,2,['C','B']));assert.equal(count(s),s.spawned);});
